### ISSUE TITLE
NullPointerException in finding a control dependence

### ISSUE THREAD

**Issue by katsuhisamaruyama** [katsuhisamaruyama/jxplatform3#6]
In analyzing the method execute() in the class com.datatorrent.stram.StreamingAppMasterService within apex-core-3.7.0 project,
at org.jtool.pdg.internal.CDFinder.simplyFindCDs(CDFinder.java:104)
        at org.jtool.pdg.internal.CDFinder.simplyFindCDs(CDFinder.java:96)
        at org.jtool.pdg.internal.CDFinder.find(CDFinder.java:52)
        at org.jtool.pdg.internal.PDGBuilder.buildPDG(PDGBuilder.java:53)
        at org.jtool.pdg.internal.PDGBuilder.buildClDG(PDGBuilder.java:35)
        at org.jtool.pdg.internal.PDGStore.generateUnregisteredClDG(PDGStore.java:442)
        at org.jtool.jxplatform.experiment.CommonGenerator.generateClDGs(CommonGenerator.java:130)
        at org.jtool.jxplatform.experiment.PDGGenerator.buildPDGs(PDGGenerator.java:99)
        at org.jtool.jxplatform.experiment.PDGGenerator.run(PDGGenerator.java:59)
        at org.jtool.jxplatform.experiment.PDGGenerator.main(PDGGenerator.java:41)

**Comment by katsuhisamaruyama** [comment]
a "statement" object is null in the following method:
```
private static void simplyFindCDs(PDG pdg, CFG cfg, CFGNode node) {
    for (ControlFlow flow : node.getOutgoingFlows()) {
        DominantStatement statement = cfg.getDominantStatement(flow);
        for (CFGNode postDominator : statement.getImmediatePostDominators()) {
            CD cd = createCD(node, flow, postDominator);
            pdg.add(cd);
        }
    }
}
```
